### PR TITLE
Improve PHPUnit fixtures

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- According to the official [PHPUnit doc](https://phpunit.readthedocs.io/en/9.5/fixtures.html#more-setup-than-teardown), it should be `protected function setUp(): void`.

### CODE REVIEW

**Comment by g105b** [comment]
Hello, thank you @peter279k for your contribution. I've noticed that I hadn't set the repository to build pull requests, but I've made this change on `master` now.

Please can you either merge `master` into this PR, or [grant permission for me to do this on your behalf](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

Thanks for your contributions.

**Comment by peter279k** [comment]
Invited. And please check your mail box :).

**Comment by g105b** [comment]
I'm missing the invitation on this repository.

**Comment by peter279k** [comment]
Resent. Please check mail box again :).

**Comment by g105b** [comment]
I'm not sure why, but I still can not push to this branch. My merge button is disabled still, and I am not able to make a merge via the CLI. I will ask Github support in case they can help.

**Comment by g105b** [comment]
image

Maybe this box is unchecked? (Taken from https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

You can do this yourself by merging master into this branch, then it will kick off the PR workflow.

**Comment by peter279k** [comment]
I don't have that checked box on the GitHub organization. I'm going to close this PR and fork this repository on my GitHub user repository.

**Pull request closed without merging**
