### PR TITLE
Add CRUD methods

### PR DESCRIPTION
**Pull request by j4m3s**
...and tests

### CODE REVIEW

**Comment by j4m3s** [comment]
It's probably evident from the tests, but if a user calls `->create("delete")` then their delete script will be run but a `null` `lastInsertID` will be returned.  

A better question though is how we handle a scenario (which could be quite common) where a user calls `->create()` expecting it to call their `create.sql` script.  As it stands it won't - instead it will throw a php error saying they have to pass-in the script name (i.e. they should call `->create("create")`).  We could automatically try that (i.e. assume `->create()` means `->create('create')`) if they don't pass in a script $name - what do you think?

**Comment by j4m3s** [comment]
(Sorry, should have said in the PR - this closes #19).

**Comment by g105b** [comment]
I've merged this in to master to avoid any confusing branching. While I decide on some sort of standardised branch management, I've created the v1 branch which doesn't include this PR yet.

**Comment by j4m3s** [comment]
Bonza.  Now you come to mention it that's how the big boys like ansible do it - they create a branch for the versions and commit bug fixes etc to master.

Did you see my question about handling scripts called "create" etc?

**Comment by g105b** [comment]
In response to your question, I think assumption should be made. Continue this discussion in #20?

**Pull request merged**
